The `viridis` color maps are designed to be perceptually-uniform, both in regular form and also when converted to black-and-white.

More info: https://bids.github.io/colormap/

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.10.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.6.1.

In [3]:
val mpg = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg2.csv")
mpg.head(3)

miles per gallon,number of cylinders,engine displacement (cu. inches),engine horsepower,vehicle weight (lbs.),time to accelerate (sec.),model year,origin of car,vehicle name
18.000000,8,307.000000,130,3504,12.000000,70,US,chevrolet chevelle malibu
15.000000,8,350.000000,165,3693,11.500000,70,US,buick skylark 320
18.000000,8,318.000000,150,3436,11.000000,70,US,plymouth satellite

In [4]:
import org.jetbrains.letsPlot.intern.Plot

fun pair(p0:Plot, p1:Plot):Figure {
    return gggrid(
            listOf(p0, p1),
            ncol = 2,
            fit = true
        ) + ggsize(1000, 300)
}

In [5]:
val pC = letsPlot(mpg.toMap()) + 
 geomPoint(size = 7) {x = "vehicle weight (lbs.)"; y = "miles per gallon"; color = "miles per gallon"} + 
 ggtitle("Continuous data") + labs(color = "MPG")

val pD = letsPlot(mpg.toMap()) + geomBar{x = "origin of car"; fill = "origin of car"} +
 ggtitle("Discrete data") + labs(fill = "")

### The "viridis" colormap is the default option.

Adjust scales with `begin, end, alpha` and `direction` parameters.

In [6]:
pair(pC + scaleColorViridis(),
     pC + scaleColorViridis(end = 0.5))

In [7]:
pair(pD + scaleFillViridis(),
     pD + scaleFillViridis(begin = 0.3, end = 0.8))

In [8]:
pair(pD + scaleFillViridis(alpha = 0.4),
     pD + scaleFillViridis(begin = 0.3, end = 0.8, direction = -1))

### Supported colormaps
Use the `option` parameter to select a colormap you like:

- "magma" (or "A"),
- "inferno" (or "B")
- "plasma" (or "C")
- "viridis" (or "D") - the default
- "cividis" (or "E")
- "turbo"
- "twilight"

#### Magma

In [9]:
pair(pC + scaleColorViridis(option = "A"),
     pD + scaleFillViridis(option = "magma"))

#### Inferno

In [10]:
pair(pC + scaleColorViridis(option = "B"),
     pD + scaleFillViridis(option = "inferno"))

#### Plasma

In [11]:
pair(pC + scaleColorViridis(option = "C"),
     pD + scaleFillViridis(option = "plasma"))

#### Viridis

In [12]:
pair(pC + scaleColorViridis(option = "D"),
     pD + scaleFillViridis(option = "viridis"))

#### Cividis

In [13]:
pair(pC + scaleColorViridis(option = "E"),
     pD + scaleFillViridis(option = "cividis"))

#### Turbo

In [14]:
pair(pC + scaleColorViridis(option = "turbo", direction = -1),
     pD + scaleFillViridis(option = "turbo"))

#### Twilight

In [15]:
pair(pC + scaleColorViridis(option = "twilight"),
     pD + scaleFillViridis(option = "twilight"))