# Flipping Coordinates

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.10.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.6.1.

In [3]:
var mpg = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
mpg.head(3)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact

## `coordFlip()`

In [4]:
val p = letsPlot(mpg.toMap()) + theme(axisTitleX="blank")

In [5]:
val boxPlot = p + 
    geomBoxplot(color="#579673", fill="#9AC0B3", size=1.5) {
        x = asDiscrete("class", order=1, orderBy="..middle..")
        y = "hwy" 
    } + 
    ggsize(750, 300)
    
boxPlot + ggtitle("Default")

In [6]:
boxPlot + ggtitle("Flipped") + coordFlip()

In [7]:
val barPlot = p + 
    geomBar(size=1.5, alpha=0.7, width=0.7) {
        x = asDiscrete("manufacturer", orderBy="..count..")
        fill = "class"
        color = "class"
    } +
    ggsize(800, 300)
    
barPlot + ggtitle("Default")

In [8]:
barPlot + ggtitle("Flipped") + coordFlip()

## Parameter `flip`

In [9]:
val pointPlot = letsPlot(mpg.toMap()) +
    geomPoint(alpha = .5, shape = 21,
              position = positionJitter(width = .2, height = .2, seed = 42))
        { x = "displ"; y = "hwy"; fill = "class" }

pointPlot + coordFixed(ratio = .1) + ggtitle("coordFixed()")

In [10]:
pointPlot + coordFixed(ratio = 10, flip = true) + ggtitle("coordFixed(flip = true)")