# Sina Plot

A sina plot visualizes a single variable across classes, with jitter width reflecting the data's density in each class.

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.12.1. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.8.2.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

In [3]:
val df = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg.csv")
val dataMap = df.toMap()
df.head()

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.000000,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.800000,1999,6,auto(l5),f,16,26,p,compact

## Default View

In [4]:
val g = letsPlot(dataMap) { x = "drv"; y = "hwy" }

In [5]:
g + geomSina(seed = 42)

## When to Use

In [6]:
gggrid(listOf(
    g + geomBoxplot() + ggtitle("geomBoxplot()", "Show distribution but not sample size"),
    g + geomViolin() + ggtitle("geomViolin()", "Show distribution but not sample size"),
    g + geomJitter(seed = 42) + ggtitle("geomJitter()", "Show sample size but not distribution"),
    g + geomSina(seed = 42) + ggtitle("geomSina()", "Show both distribution and sample size"),
), ncol = 2)

## Applying Jitter Position

Sometimes vertically adjusting points might be desirable:

- **overlapping values**, where multiple observations share the exact same y-value;

- **integerish banding**, where values are close to integers and appear artificially grouped into horizontal bands.

In these cases, you may consider using a position adjustment.

In [7]:
gggrid(listOf(
    g + geomSina(seed = 42) + ggtitle("Default position"),
    g + geomSina(seed = 42, position = positionJitter(width = 0, seed = 42)) + ggtitle("'jitter' position"),
))

Use the `'jitterdodge'` position adjustment if additional grouping is required:

In [8]:
gggrid(listOf(
    g + geomSina(seed = 42) { color = asDiscrete("year") } +
        scaleColorDiscrete(format = "d") +
        ggtitle("Default position"),
    g + geomSina(seed = 42, position = positionJitterDodge(jitterWidth = 0, seed = 42))
            { color = asDiscrete("year") } +
        scaleColorDiscrete(format = "d") +
        ggtitle("'jitterdodge' position"),
))

## Connection with Violins

In a sina plot, points are randomly positioned within a violin plot using the same parameters.

### Same Shape

In [9]:
g +
    geomViolin(bw = 1.5) +
    geomSina(bw = 1.5, seed = 42)

### Same Quantiles

In [10]:
g +
    geomViolin(alpha = .5) { color = "..quantile.."; fill = "..quantile.." } +
    geomSina(size = 2, seed = 42) { color = "..quantile.." } +
    scaleContinuous(listOf("color", "fill"), otherOptions = mapOf("low" to "green", "high" to "red"))

### Same `scale` Values

In [11]:
gggrid(listOf(
    g +
        geomViolin(scale = "width") +
        geomSina(scale = "width", size = 1.5, seed = 42) +
        ggtitle("scale = \"width\""),
    g +
        geomViolin(scale = "area") +
        geomSina(scale = "area", size = 1.5, seed = 42) +
        ggtitle("scale = \"area\""),
    g +
        geomViolin(scale = "count") +
        geomSina(scale = "count", size = 1.5, seed = 42) +
        ggtitle("scale = \"count\""),
))

### Compatible Stats

In [12]:
gggrid(listOf(
    g + geomViolin() + ggtitle("Violin\nstat = Stat.yDensity() (default)"),
    g + geomViolin(stat = Stat.sina()) + ggtitle("Violin\nstat = Stat.sina()"),
    g + geomSina(size = 1.5, seed = 42, stat = Stat.yDensity()) + ggtitle("Sina\nstat = Stat.yDensity()"),
    g + geomSina(size = 1.5, seed = 42) + ggtitle("Sina\nstat = Stat.sina() (default)"),
), ncol = 2)

### `showHalf` Parameter

In [13]:
g +
    geomViolin(showHalf = -1, size = 0, fill = "gray85") +
    geomSina(showHalf = 1, seed = 42)

### Raincloud Plot

In [14]:
g +
    geomViolin(showHalf = 1, size = 0, position = positionNudge(x = .07)) { fill = "drv" } +
    geomBoxplot(color = "white", width = .1, outlierAlpha = 0, showLegend = false) { fill = "drv" } +
    geomSina(showHalf = -1, seed = 42, position = positionNudge(x = -.07), showLegend = false)
        { color="drv" } +
    scaleColorBrewer(palette = "Set2") +
    scaleFillBrewer(palette = "Pastel2") +
    facetGrid(x = "year", xFormat = "d") +
    coordFlip() +
    themeLight() + flavorSolarizedDark()