### Y-Dotplot Geometry

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.12.1. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.8.2.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

In [3]:
var mpg = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
mpg.head()

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.000000,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.800000,1999,6,auto(l5),f,16,26,p,compact

In [4]:
val mpg100 = mpg.shuffle().take(100)

In [5]:
letsPlot(mpg100.toMap()) + geomYDotplot {y = "hwy"}

### `geomDotplot()` and `geomViolin()`

In [6]:
val PACIFIC_BLUE = "#118ed8"

In [7]:
val plotBase = letsPlot(mpg100.toMap()) {x = "drv"; y = "hwy"}

In [8]:
val plots = listOf(
    plotBase +
    geomViolin(fill = PACIFIC_BLUE, size = 0) + 
    geomYDotplot(binWidth = 1.6, stackRatio=.5, fill = "white", color = PACIFIC_BLUE) + 
    ggtitle("violin + ydotplot (method='dotdensity')"),
    plotBase +
    geomViolin(fill = PACIFIC_BLUE, size = 0) + 
    geomYDotplot(binWidth = 1.6, stackRatio=.5, method = "histodot", fill = "white", color = PACIFIC_BLUE) + 
    ggtitle("violin + ydotplot (method='histodot')"),
)

gggrid(plots, 2) + ggsize(900, 300)

### Parameter `stackDir`

In [9]:
val plots1 = listOf(
    plotBase + geomYDotplot(binWidth = 1.5, stackDir = "left") + ggtitle("stackDir = \"left\""),
    plotBase + geomYDotplot(binWidth = 1.5, stackDir = "right") + ggtitle("stackDir = \"right\""),
    plotBase + geomYDotplot(binWidth = 1.5, stackDir = "center") + ggtitle("stackDir = \"center\""),
    plotBase + geomYDotplot(binWidth = 1.5, stackDir = "centerwhole") + ggtitle("stackDir = \"centerwhole\""),
)

gggrid(plots1, 2) + ggsize(900, 600)

### Parameter `stackRatio`

In [10]:
val plots2 = listOf(
    plotBase + geomYDotplot(binWidth = 1.5, stackRatio = 1) + ggtitle("stackRatio = 1"),
    plotBase + geomYDotplot(binWidth = 1.5, stackRatio = 0.5) + ggtitle("stackRatio = 0.5"),
    plotBase + geomYDotplot(binWidth = 1.5, stackRatio = 1.5) + ggtitle("stackRatio = 1.5"),
)

gggrid(plots2, 2) + ggsize(900, 600)

### Parameter `dotSize`

In [11]:
val plots3 = listOf(
    plotBase + geomYDotplot(binWidth = 1.5, dotSize = 1) + ggtitle("dotSize = 1"),
    plotBase + geomYDotplot(binWidth = 1.5, dotSize = 0.5) + ggtitle("dotSize = 0.5"),
    plotBase + geomYDotplot(binWidth = 1.5, dotSize = 1.5) + ggtitle("dotSize = 1.5"),
)

gggrid(plots3, 2) + ggsize(900, 600)

### Parameter `center`

In [12]:
val plots4 = listOf(
    plotBase + geomYDotplot(binWidth = 1.5, method = "histodot") + ggtitle("Default"),
    plotBase + geomYDotplot(binWidth = 1.5, method = "histodot", center = 11) + ggtitle("center = 11"),
)

gggrid(plots4, 2) + ggsize(900, 300)

### Parameter `boundary`

In [13]:
val plots5 = listOf(
    plotBase + geomYDotplot(binWidth = 1.5, method = "histodot") + ggtitle("Default"),
    plotBase + geomYDotplot(binWidth = 1.5, method = "histodot", boundary = 12) + ggtitle("boundary = 12"),
)

gggrid(plots5, 2) + ggsize(900, 300)

### Parameter `bins`

In [14]:
val plots6 = listOf(
    plotBase + geomYDotplot(method = "histodot") + ggtitle("Default (30)"),
    plotBase + geomYDotplot(method = "histodot", bins = 15) + ggtitle("bins = 15"),
)

gggrid(plots6, 2) + ggsize(900, 300)

### Grouping

In [15]:
val plots7 = listOf(
    plotBase + geomYDotplot(binWidth = 1.6, stackRatio = .75, color = "white") {
        fill = asDiscrete("year")
    } +
        scaleFillDiscrete(format = "d") +
        ggtitle("method = \"dotdensity\", stackGroups = false (default)"),
    plotBase + geomYDotplot(binWidth = 1.6, stackRatio = .75, color = "white", 
                            stackGroups = true) {
        fill = asDiscrete("year")
    } +
        scaleFillDiscrete(format = "d") +
        ggtitle("method = \"dotdensity\", stackGroups = true"),
    plotBase + geomYDotplot(binWidth = 1.6, stackRatio = .75, color = "white", 
                            stackGroups = true, method = "histodot") {
        fill = asDiscrete("year")
    } +
        scaleFillDiscrete(format = "d") +
        ggtitle("method = \"dotdensity\", stackGroups = true"),
)

gggrid(plots7, 1, fit = true) + ggsize(800, 1200)

### Tooltips

In [16]:
letsPlot(mpg100.toMap()) {x = "drv"; y = "hwy"} + 
    geomYDotplot(tooltips = layerTooltips()
                    .title("Drivetrain: ^x")
                    .line("stack center|^y")
                    .line("Number of dots in stack|@..count..")
                    .line("Dot diameter|@..binwidth..")
               )

### Facets

In [17]:
val plotBase2 = plotBase + 
    scaleColorBrewer(type="qual", palette="Set1") + 
    scaleFillBrewer(type="qual", palette="Set1") +
    themeGrey()

In [18]:
plotBase2 + geomYDotplot(binWidth = 1.5) {
        color = asDiscrete("drv")
        fill = asDiscrete("drv")
    } + facetGrid(x = "year", xFormat = "d") + ggtitle("facetGrid")

### `coordFlip()`

In [19]:
letsPlot(mpg100.toMap()) + geomYDotplot(binWidth = 1.5, stackRatio = .3, dotSize = .8, color = "white") {
    x = "drv"; y = "hwy"; fill = "drv"
} + coordFlip()