In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.9.3. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.5.2.

In [3]:
val df = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
df.head(3)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact

In [4]:
val p = letsPlot(df.toMap()) { x = "cty"; y = "hwy"; color = "drv" } + geomPoint() + labs(color="Drive type") 
p

In [5]:
// Horizontal justification for plot title, subtitle, caption, legend and axis titles

val hjustLeft = elementText(hjust = 0.0)
val hjustMiddle = elementText(hjust = 0.5)
val hjustRight = elementText(hjust = 1.0)


fun withHJjust(hjust: Map<String, Any>): org.jetbrains.letsPlot.intern.OptionsMap {
    return theme(title = hjust, axisTitle = hjust, plotCaption = hjust, legendTitle = hjust)
}

val p2 = p + labs(caption = "The plot caption")


gggrid(
    plots = listOf(
        p2 + withHJjust(hjustLeft) + ggtitle("All titles with hjust = 0.0"),
        p2 + withHJjust(hjustMiddle) + ggtitle("All titles with hjust = 0.5"),
        p2 + withHJjust(hjustRight) + ggtitle("All titles with hjust = 1.0"),
    ),
    ncol = 1,
    cellWidth = 600,
    cellHeight = 400,
    fit = true
)

In [6]:
// Vertical justification for legend title

val vjustBottom = elementText(vjust =0.0)
val vjustCenter = elementText(vjust = 0.5)
val vjustTop = elementText(vjust = 1.0)

fun withVJjust(vjust: Map<String, Any>): org.jetbrains.letsPlot.intern.OptionsMap {
    return theme(legendTitle = vjust)
}

val p3 = p + theme().legendPositionBottom() + scaleColorDiscrete(guide = guideLegend(ncol = 1))

gggrid(
    plots = listOf(
        p3 + withVJjust(vjustBottom) + ggtitle("Legend title with vjust = 0.0"),
        p3 + withVJjust(vjustCenter) + ggtitle("Legend title with vjust = 0.5"),
        p3 + withVJjust(vjustTop) + ggtitle("Legend title with vjust = 1.0"),
    ),
    ncol = 1,
    cellWidth = 600,
    cellHeight = 400,
    fit = true
)