# Customizing the Legend

In [1]:
%useLatestDescriptors
%use lets-plot
%use dataframe

In [2]:
val df = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
df.head()

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.000000,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.800000,1999,6,auto(l5),f,16,26,p,compact

In [3]:
val mpg = df.toMap()

## Scale Parameters Related to the Legend

In [4]:
// Default legend
val p1 = letsPlot(mpg) { x = "cty"; y = "hwy" } + geomPoint() { color = "cyl" }
p1

In [5]:
// Legend name
p1 + scaleColorContinuous(name = "Number of cylinders")

In [6]:
// Breaks and labels
p1 + scaleColorContinuous(breaks = listOf(4, 5, 6, 8), labels = listOf("four", "five", "six", "eight"))

In [7]:
// Format labels
p1 + scaleColorContinuous(format = "{} cylinders\nin the vehicle’s engine")

## Guides

### `guideLegend()`

In [8]:
// Default categorical legend
val p2 = letsPlot(mpg) { x = "displ"; y = "hwy"; color = "manufacturer" } + geomPoint(size = 5)
p2

In [9]:
// Legend name
p2 + scaleColorDiscrete(guide = guideLegend("Company"))

In [10]:
// Layout the legend in two columns
p2 + scaleColorDiscrete(guide = guideLegend(ncol = 2))

In [11]:
// Fill by rows
p2 + scaleColorDiscrete(guide = guideLegend(ncol = 2, byRow = true))

### `guideColorbar()`

In [12]:
// Default color legend
val p3 = letsPlot(mpg) { x = "displ"; y = "hwy" } + geomPoint() { color = "cty" }
p3

In [13]:
// Legend name
p3 + scaleColorContinuous(guide = guideColorbar("City mileage"))

In [14]:
// Adjust colorbar size
p3 + scaleColorContinuous(guide = guideColorbar(barWidth = 10, barHeight = 200))

In [15]:
// Fewer bins
p3 + scaleColorContinuous(breaks = listOf(13, 22, 31), guide = guideColorbar(nbin = 3))

### `guides()`

In [16]:
// Default complex legend
val p4 = letsPlot(mpg) { x = "displ"; y = "hwy" } + geomPoint(size = 5) { color = "cty"; shape = "drv" }
p4

In [17]:
// Guides for 'color' and 'shape' aesthetics
p4 + guides(color = guideColorbar(barWidth = 10), shape = guideLegend(ncol = 2))

### Customizing Legend Appearance

In [18]:
p4 + guides(shape = guideLegend(size = 8, color = "#f03b20"))

## Legend Position

In [19]:
// Draw legend below the plot area
p4 + theme().legendPositionBottom()

In [20]:
// Specify position, justification and orientation
p4 + theme().legendPosition(1, 1).legendJustification(1, 1).legendDirectionHorizontal()