In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.10.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.6.1.

In [3]:
var mpg = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
mpg.head(3)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact

In [4]:
val p = letsPlot(mpg.toMap()) + geomPoint { x = "cty"; y = "hwy"}

In [5]:
val (w, h) = 400 to 300
val e_rect = elementRect(color="#9e9eff", fill="#f0f8ff", size=8)

// compare theme parameters: panelBackground and panelBorder.
// Note: panelBorder ignores the "fill" setting.

gggrid(listOf(
    p + ggtitle("panel_background=e_rect") + theme(panelBackground=e_rect),
    p + ggtitle("panel_border=e_rect") + theme(panelBorder=e_rect)
)) + ggsize(2 * w, h)